Jenkins integration
Kuunika/MHFR pull request #18
Opened 2021-03-04 11:34 UTC by Loui4

2021-03-09 07:57 UTC, bwighane requested changes

2021-03-09 07:57 UTC, bwighane commented on Dockerfile
> +CMD [ "pm2-runtime", "server/server.j" ]
Does this work when  tested? I see you have missed an "s" at the end

2021-03-09 07:58 UTC, bwighane commented
Hey @Loui4 , I simply forgot to submit after reviewing the commit. Apologies for that.

2021-03-12 07:13 UTC, Loui4 commented on Dockerfile
> +CMD [ "pm2-runtime", "server/server.j" ]
I tested it was working but I think I did some refactorings just before committing which I accidentally omitted the s.

2021-03-12 07:16 UTC, bwighane commented on Dockerfile
> +CMD [ "pm2-runtime", "server/server.j" ]
Cool

2021-03-12 07:16 UTC, bwighane approved these changes

2021-03-12 07:16 UTC, merged